services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - .env.test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d postgres -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork
  backend:
    image: daily-kindness-backend
    container_name: daily-kindness-backend
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - .env.test
    networks:
      - mynetwork
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run test:ci

networks:
  mynetwork:
    name: mynetwork
