services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - back-end/.env.test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d postgres -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    image: bingo-backend
    container_name: bingo-backend
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - back-end/.env.test